# add your desired knowledge graph components here

investigation:
    is_a: activity
    represented_as: node
    preferred_id: investigation
    input_label: investigation
    properties:
        hasName: str
        hasDescription: str
        hasIdentifier: str
        hasMIAPPEVersion: str

study:
    represented_as: node
    preferred_id: study
    input_label: study
    properties:
        hasName: str
        hasDescription: str
        hasStartDateTime: str
        hasEndDateTime: str
        hasIdentifier: str
        hasCulturalPractices: str
        hasObservationUnitDescription: str


biological material:
    is_a: biological entity
    preferred_id: Biological Material
    represented_as: node
    input_label: biologicalMaterial
    properties:
            hasGenus: str
            hasSpecies: str
            hasMaterialIdentifier: str
            hasTaxonIdentifier: str

observation unit:
    is_a: information content entity
    preferred_id: ObsUnit
    represented_as: node
    input_label: obs_unit
    properties:
        hasInternalIdentifier: str


sample:
    is_a: material sample
    preferred_id: Sample
    represented_as: node
    input_label: sample
    properties:
        hasCollectionDate: str
        hasDescription: str
        hasExternalIdentifier: str
        hasInternalIdentifier: str
        hasPlantAnatomicalEntity: str
        hasPlantStructureDevelopmentStage: str


observed variable:
    is_a: study variable
    preferred_id: ObsVar
    represented_as: node
    input_label: obs_var
    properties:
        hasExternalIdentifier: str
        hasInternalIdentifier: str
        hasName: str

trait:
    is_a: attribute
    preferred_id: trait
    represented_as: node
    input_label: trait
    properties:
        hasExternalIdentifier: str
        hasName: str

has trait:
    is_a: association
    represented_as: edge
    input_label: hasTrait

has part:
    is_a: association
    represented_as: edge
    input_label: hasPart

part of:
    is_a: association
    represented_as: edge
    input_label: partOf

has biological material:
    is_a: association
    represented_as: edge
    input_label: hasBiologicalMaterial

derives from:
    is_a: association
    represented_as: edge
    input_label: derivesFrom


#has part:
#    is_a: "has part"
#    represented_as: edge
#    preferred_id: http://purl.org/ppeo/PPEO.owl#hasPart
#    input_label: hasPart
#    properties:
#        name: str
#        category: str


#protein:
#    represented_as: node
#    preferred_id: uniprot
#    input_label: uniprot_protein

#disease:
#    represented_as: node
#    preferred_id: doid
#    input_label: do_disease

#protein interaction:
#    is_a: pairwise molecular interaction
#    represented_as: edge
#    input_label: protein_protein_interaction

#protein to disease association:
#    is_a: association
#    represented_as: edge
#    input_label: protein_disease_association
