# add your desired knowledge graph components here

## Documentation
# https://biocypher.org/quickstart.html#the-schema-configuration-yaml-file
# is_a: to define the node name as something different from the name



investigation:
    ## Must be equal to the label in the class definition of the ontological term. No camelCase is allowed.
    #is_a: technological concept
    represented_as: node
    preferred_id: Investigation
    #The label given in the node parameters
    input_label: investigation
    properties:
        name: str
        description: str
        identifier: str
        MIAPPE version: str
        associated publication: str

study:
    represented_as: node
    preferred_id: study
    input_label: study
    properties:
        name: str
        description: str
        start date time: str
        end date time: str
        identifier: str
        cultural practices: str
        observation unit description: str


biological material:
    preferred_id: Bio Material
    represented_as: node
    input_label: biological material
    properties:
        hasGenus: str
        hasSpecies: str
        hasMaterialIdentifier: str
        hasTaxonIdentifier: str

observation unit:
    #is_a: information content entity
    preferred_id: ObsUnit
    represented_as: node
    input_label: observation unit
    properties:
        hasInternalIdentifier: str


sample:
    #is_a: material sample
    preferred_id: Sample
    represented_as: node
    input_label: sample
    properties:
        hasCollectionDate: str
        hasDescription: str
        hasExternalIdentifier: str
        hasInternalIdentifier: str
        hasPlantAnatomicalEntity: str
        hasPlantStructureDevelopmentStage: str

observed variable:
    #is_a: study variable
    preferred_id: ObsVar
    represented_as: node
    input_label: observedVariable
    properties:
        hasExternalIdentifier: str
        hasInternalIdentifier: str
        hasName: str

trait:
    #is_a: phenotypic feature
    preferred_id: trait
    represented_as: node
    input_label: trait
    properties:
        hasExternalIdentifier: str
        hasName: str


#################
#### edges ######
#################

#example with directed edge:
#    is_a: association
#    represented_as: edge
#    input_label: hasTrait
#    #source: dfjhsfkjhsdjk
#    #target: hkjsdfhjsfh


has part:
    is_a: association
    represented_as: edge
    input_label: has part

part of:
    is_a: association
    represented_as: edge
    input_label: part of

has biological material:
    is_a: association
    represented_as: edge
    input_label: has biological material

derives from:
    is_a: association
    represented_as: edge
    input_label: derivesFrom

has variable:
    is_a: association
    represented_as: edge
    input_label: has variable
